# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='Ghana', max_length=100),
        ),
    ]
